[package]
name = "imgbank"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.3.4" 
lodepng = "3.4.5"
libgfx = {path = "../libgfx"}
libsprite = {path = "../libsprite"}
toml = "0.5.6" 
pico-args = "0.4.0"
indoc = "1.0"
